apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecart-deployment
spec:
  selector:
    matchLabels:
      app: ecart
  replicas: 2 
  template:
    metadata:
      labels:
        app: ecart
    spec:
      containers:
        - name: ecart
          image: momagdyy/ecart:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 



